# Generated by Django 2.1 on 2019-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('poster', models.ImageField(upload_to='')),
                ('rented', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
