# Generated by Django 2.1 on 2019-03-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0002_auto_20190320_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
