# Generated by Django 2.1 on 2019-03-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0004_auto_20190320_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
