# Generated by Django 2.1 on 2019-03-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0005_auto_20190320_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rented',
            field=models.IntegerField(default=0),
        ),
    ]
