# Generated by Django 2.1 on 2019-03-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0006_movie_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stock',
            new_name='in_stock',
        ),
    ]
