# Generated by Django 2.1 on 2019-03-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0007_auto_20190321_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='in_stock',
            new_name='stock',
        ),
    ]
