# Generated by Django 2.1 on 2019-03-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0010_auto_20190321_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedmovie',
            name='movie',
        ),
        migrations.AddField(
            model_name='rentedmovie',
            name='movie',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='videorental.Movie'),
        ),
    ]
