# Generated by Django 2.1 on 2019-03-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0011_auto_20190321_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videorental.Movie'),
        ),
    ]
