# Generated by Django 2.1 on 2019-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorental', '0012_auto_20190322_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sumary',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
